FROM maven:3.6.0-jdk-8-alpine AS web

RUN apk update && \
    apk upgrade && \
    apk add --no-cache openssl

COPY . ./app
WORKDIR /app

RUN mvn clean package -DskipTests -pl development-team-web-app -am

FROM openjdk:8

WORKDIR /app

COPY --from=web /app/development-team-web-app/target/*.jar  /app

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/web_app_DT.jar"]