version: "3.7"

services:
  mysql-service:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
  web-service:
    build:
      context: ./development-team-rest-soap
      dockerfile: Dockerfile
    ports:
      - "8088:4000"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service

networks:
  spring-boot-mysql-network:
    driver: bridge