version: "3.7"

services:
  mysql-service:
    image: mysql:latest
    build:
      context: ./
      dockerfile: Dockerfile-db
    restart: always
    ports:
      - "3307:3306"
    networks:
      - my_mysql_net
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
networks:
  my_mysql_net:
    driver: bridge