//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.29 at 07:11:34 PM MSK 
//


package com.epam.brest.courses.soap_api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="projects_developersInfo" type="{http://epam.com/brest/courses/soap_api}projects_developersInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectsDevelopersInfo"
})
@XmlRootElement(name = "findByIdFromProjects_DevelopersResponse")
public class FindByIdFromProjectsDevelopersResponse {

    @XmlElement(name = "projects_developersInfo", required = true)
    protected ProjectsDevelopersInfo projectsDevelopersInfo;

    /**
     * Gets the value of the projectsDevelopersInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectsDevelopersInfo }
     *     
     */
    public ProjectsDevelopersInfo getProjectsDevelopersInfo() {
        return projectsDevelopersInfo;
    }

    /**
     * Sets the value of the projectsDevelopersInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectsDevelopersInfo }
     *     
     */
    public void setProjectsDevelopersInfo(ProjectsDevelopersInfo value) {
        this.projectsDevelopersInfo = value;
    }

}
