//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.29 at 07:11:34 PM MSK 
//


package com.epam.brest.courses.soap_api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.brest.courses.soap_api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.brest.courses.soap_api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindAllDevelopersResponse }
     * 
     */
    public FindAllDevelopersResponse createFindAllDevelopersResponse() {
        return new FindAllDevelopersResponse();
    }

    /**
     * Create an instance of {@link DeveloperInfo }
     * 
     */
    public DeveloperInfo createDeveloperInfo() {
        return new DeveloperInfo();
    }

    /**
     * Create an instance of {@link UpdateProjectResponse }
     * 
     */
    public UpdateProjectResponse createUpdateProjectResponse() {
        return new UpdateProjectResponse();
    }

    /**
     * Create an instance of {@link CountOfDevelopersRequest }
     * 
     */
    public CountOfDevelopersRequest createCountOfDevelopersRequest() {
        return new CountOfDevelopersRequest();
    }

    /**
     * Create an instance of {@link DeleteDeveloperRequest }
     * 
     */
    public DeleteDeveloperRequest createDeleteDeveloperRequest() {
        return new DeleteDeveloperRequest();
    }

    /**
     * Create an instance of {@link DeleteProjectRequest }
     * 
     */
    public DeleteProjectRequest createDeleteProjectRequest() {
        return new DeleteProjectRequest();
    }

    /**
     * Create an instance of {@link GetAllProjectsRequest }
     * 
     */
    public GetAllProjectsRequest createGetAllProjectsRequest() {
        return new GetAllProjectsRequest();
    }

    /**
     * Create an instance of {@link UpdateDeveloperResponse }
     * 
     */
    public UpdateDeveloperResponse createUpdateDeveloperResponse() {
        return new UpdateDeveloperResponse();
    }

    /**
     * Create an instance of {@link FindByDeveloperIdRequest }
     * 
     */
    public FindByDeveloperIdRequest createFindByDeveloperIdRequest() {
        return new FindByDeveloperIdRequest();
    }

    /**
     * Create an instance of {@link SelectDevelopersFromProjectsDevelopersResponse }
     * 
     */
    public SelectDevelopersFromProjectsDevelopersResponse createSelectDevelopersFromProjectsDevelopersResponse() {
        return new SelectDevelopersFromProjectsDevelopersResponse();
    }

    /**
     * Create an instance of {@link ProjectsDevelopersInfo }
     * 
     */
    public ProjectsDevelopersInfo createProjectsDevelopersInfo() {
        return new ProjectsDevelopersInfo();
    }

    /**
     * Create an instance of {@link FindAllByDateAddedBetweenRequest }
     * 
     */
    public FindAllByDateAddedBetweenRequest createFindAllByDateAddedBetweenRequest() {
        return new FindAllByDateAddedBetweenRequest();
    }

    /**
     * Create an instance of {@link CreateDeveloperResponse }
     * 
     */
    public CreateDeveloperResponse createCreateDeveloperResponse() {
        return new CreateDeveloperResponse();
    }

    /**
     * Create an instance of {@link AddDeveloperToProjectsDevelopersRequest }
     * 
     */
    public AddDeveloperToProjectsDevelopersRequest createAddDeveloperToProjectsDevelopersRequest() {
        return new AddDeveloperToProjectsDevelopersRequest();
    }

    /**
     * Create an instance of {@link GetAllProjectsResponse }
     * 
     */
    public GetAllProjectsResponse createGetAllProjectsResponse() {
        return new GetAllProjectsResponse();
    }

    /**
     * Create an instance of {@link ProjectInfo }
     * 
     */
    public ProjectInfo createProjectInfo() {
        return new ProjectInfo();
    }

    /**
     * Create an instance of {@link FindAllDevelopersRequest }
     * 
     */
    public FindAllDevelopersRequest createFindAllDevelopersRequest() {
        return new FindAllDevelopersRequest();
    }

    /**
     * Create an instance of {@link CreateDeveloperRequest }
     * 
     */
    public CreateDeveloperRequest createCreateDeveloperRequest() {
        return new CreateDeveloperRequest();
    }

    /**
     * Create an instance of {@link FindDevByDeveloperIdRequest }
     * 
     */
    public FindDevByDeveloperIdRequest createFindDevByDeveloperIdRequest() {
        return new FindDevByDeveloperIdRequest();
    }

    /**
     * Create an instance of {@link DeleteDeveloperToProjectsDevelopersResponse }
     * 
     */
    public DeleteDeveloperToProjectsDevelopersResponse createDeleteDeveloperToProjectsDevelopersResponse() {
        return new DeleteDeveloperToProjectsDevelopersResponse();
    }

    /**
     * Create an instance of {@link FindByDeveloperIdResponse }
     * 
     */
    public FindByDeveloperIdResponse createFindByDeveloperIdResponse() {
        return new FindByDeveloperIdResponse();
    }

    /**
     * Create an instance of {@link FindDevByDeveloperIdResponse }
     * 
     */
    public FindDevByDeveloperIdResponse createFindDevByDeveloperIdResponse() {
        return new FindDevByDeveloperIdResponse();
    }

    /**
     * Create an instance of {@link FindAllByDateAddedBetweenResponse }
     * 
     */
    public FindAllByDateAddedBetweenResponse createFindAllByDateAddedBetweenResponse() {
        return new FindAllByDateAddedBetweenResponse();
    }

    /**
     * Create an instance of {@link ProjectDtoInfo }
     * 
     */
    public ProjectDtoInfo createProjectDtoInfo() {
        return new ProjectDtoInfo();
    }

    /**
     * Create an instance of {@link FindByIdFromProjectsDevelopersRequest }
     * 
     */
    public FindByIdFromProjectsDevelopersRequest createFindByIdFromProjectsDevelopersRequest() {
        return new FindByIdFromProjectsDevelopersRequest();
    }

    /**
     * Create an instance of {@link DeleteDeveloperResponse }
     * 
     */
    public DeleteDeveloperResponse createDeleteDeveloperResponse() {
        return new DeleteDeveloperResponse();
    }

    /**
     * Create an instance of {@link DeleteDeveloperToProjectsDevelopersRequest }
     * 
     */
    public DeleteDeveloperToProjectsDevelopersRequest createDeleteDeveloperToProjectsDevelopersRequest() {
        return new DeleteDeveloperToProjectsDevelopersRequest();
    }

    /**
     * Create an instance of {@link CountOfDevelopersResponse }
     * 
     */
    public CountOfDevelopersResponse createCountOfDevelopersResponse() {
        return new CountOfDevelopersResponse();
    }

    /**
     * Create an instance of {@link CreateProjectRequest }
     * 
     */
    public CreateProjectRequest createCreateProjectRequest() {
        return new CreateProjectRequest();
    }

    /**
     * Create an instance of {@link DeleteProjectResponse }
     * 
     */
    public DeleteProjectResponse createDeleteProjectResponse() {
        return new DeleteProjectResponse();
    }

    /**
     * Create an instance of {@link SelectDevelopersFromProjectsDevelopersRequest }
     * 
     */
    public SelectDevelopersFromProjectsDevelopersRequest createSelectDevelopersFromProjectsDevelopersRequest() {
        return new SelectDevelopersFromProjectsDevelopersRequest();
    }

    /**
     * Create an instance of {@link UpdateProjectRequest }
     * 
     */
    public UpdateProjectRequest createUpdateProjectRequest() {
        return new UpdateProjectRequest();
    }

    /**
     * Create an instance of {@link CreateProjectResponse }
     * 
     */
    public CreateProjectResponse createCreateProjectResponse() {
        return new CreateProjectResponse();
    }

    /**
     * Create an instance of {@link UpdateDeveloperRequest }
     * 
     */
    public UpdateDeveloperRequest createUpdateDeveloperRequest() {
        return new UpdateDeveloperRequest();
    }

    /**
     * Create an instance of {@link AddDeveloperToProjectsDevelopersResponse }
     * 
     */
    public AddDeveloperToProjectsDevelopersResponse createAddDeveloperToProjectsDevelopersResponse() {
        return new AddDeveloperToProjectsDevelopersResponse();
    }

    /**
     * Create an instance of {@link FindByIdFromProjectsDevelopersResponse }
     * 
     */
    public FindByIdFromProjectsDevelopersResponse createFindByIdFromProjectsDevelopersResponse() {
        return new FindByIdFromProjectsDevelopersResponse();
    }

}
